Numpy Arrays

In [103]:
import sys
import numpy as np
import random

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1, 2, 3,4], dtype=np.float)

C:\Users\Dragan\AppData\Local\Temp\ipykernel_6716\3503316417.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3,4], dtype=np.float)


array([1., 2., 3., 4.])

In [18]:
np.array([1, 2, 3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

In [21]:
d = np.array([{'a':1}, sys])

In [22]:
d.dtype

dtype('O')

Dimensions and Shapes

In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [25]:
A.shape

(2, 3)

In [26]:
A.ndim

2

In [27]:
A.size

6

In [28]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [29]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [30]:
B.shape

(2, 2, 3)

In [31]:
B.ndim

3

In [32]:
B.size

12

If the shape isn't consistant. It's just fall back to regular Python objects

In [33]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\Dragan\AppData\Local\Temp\ipykernel_6716\548599459.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [34]:
C.dtype

dtype('O')

In [35]:
C.shape

(2,)

In [36]:
C.size

2

In [37]:
type(C[0])

list

Indexing and Slicing of Matrics

In [38]:
# Square matrics
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [39]:
A[1]

array([4, 5, 6])

In [46]:
# A[d1, d2, d3, d4]

In [40]:
A[0]

array([1, 2, 3])

In [41]:
A[1][0]

4

In [42]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [44]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [52]:
A[1] = np.array([37, 37, 37])

In [53]:
A

array([[ 1,  2,  3],
       [37, 37, 37],
       [77, 77, 77]])

In [54]:
A[2] = 90
A

array([[ 1,  2,  3],
       [37, 37, 37],
       [90, 90, 90]])

Summary statistics

In [55]:
a = np.array([1, 2, 3, 4])

In [56]:
a.sum()

10

In [57]:
a.mean()

2.5

In [61]:
a.std()

1.118033988749895

In [62]:
a.var()

1.25

In [63]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.sum()

45

In [64]:
A.mean()

5.0

In [65]:
A.std()

2.581988897471611

In [66]:
A.sum(axis=1)

array([ 6, 15, 24])

In [67]:
A.mean(axis=1)

array([2., 5., 8.])

In [68]:
A.mean(axis=0)

array([4., 5., 6.])

In [69]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [70]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and Vectorized operations(vectorized operations are operations performed between both arrays and arrays and arrays and scalars, like in this case right here. They are optimized to be extremely fast.

In [71]:
a = np.arange(4)

In [72]:
a

array([0, 1, 2, 3])

In [73]:
# sum the entire array
a + 10

array([10, 11, 12, 13])

In [74]:
# adding to all elements
a += 100

In [75]:
a

array([100, 101, 102, 103])

In [76]:
l = [0, 1, 2, 3]

In [78]:
# list comprehension
[i + 10 for i in l]

[10, 11, 12, 13]

In [79]:
a = np.arange(4)

In [80]:
a

array([0, 1, 2, 3])

In [81]:
b = np.array([10, 10, 10, 10])

In [82]:
a + b

array([10, 11, 12, 13])

In [83]:
a * b

array([ 0, 10, 20, 30])

Boolean arrays
also called masks

In [88]:
a =np.arange(4)
a

array([0, 1, 2, 3])

In [91]:
#Selecting data, first way
a [[0, -1]]

array([0, 3])

In [92]:
# second way
a[0], a[-1]

(0, 3)

In [93]:
# third way
a[[True, False, False, True]]

array([0, 3])

In [94]:
# condition
a >= 2

array([False, False,  True,  True])

In [95]:
a[a>=2]

array([2, 3])

In [96]:
a.mean()

1.5

In [97]:
a[a > a.mean()]

array([2, 3])

In [98]:
a[~(a > a.mean())]

array([0, 1])

In [99]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [100]:
a[(a <= 2) | (a % 2 == 0)]

array([0, 1, 2])

In [105]:
A = np.random.randint(100, size=(3, 3))

In [106]:
A

array([[48, 11, 55],
       [90, 29, 58],
       [19, 94, 49]])

In [107]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([48, 55, 29, 19, 49])

In [108]:
A > 30

array([[ True, False,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [110]:
A[A>30]

array([48, 55, 90, 58, 94, 49])

In [ ]:
Linear Algebra

In [111]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [112]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [113]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [114]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [115]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [116]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in Memory
int, floats

In [119]:
# An integer in Python is > 24bytes of memory to store num. 1
sys.getsizeof(1)

28

In [120]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [121]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [122]:
np.dtype(float).itemsize

8

Lists are even larger

In [123]:
# A one element list
sys.getsizeof([1])

64

In [124]:
# An array of one element in numpy
np.array([1]).nbytes

4

And performance is also important

In [125]:
l = list(range(1000))

In [126]:
a = np.arange(1000)

In [127]:
%time np.sum(a ** 2)

Wall time: 0 ns


332833500

In [128]:
%time sum([x == 2 for x in l])

Wall time: 0 ns


1

Useful Numpy functions

RANDOM

In [130]:
np.random.random(size=2)

array([0.26640808, 0.20493989])

In [131]:
np.random.normal(size=2)

array([ 1.17807486, -1.8147938 ])

In [132]:
np.random.rand(2, 4)

array([[0.59071842, 0.99418032, 0.77494419, 0.31970553],
       [0.12953581, 0.1012299 , 0.76326278, 0.30602813]])

ARANGE

In [133]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [135]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [136]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [137]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

LINSPACE

In [138]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [139]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [140]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

ZEROS, ONES, EMPTY

In [141]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [142]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [143]:
np.zeros((3,3), dtype=np.int)

C:\Users\Dragan\AppData\Local\Temp\ipykernel_6716\179700837.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3,3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [144]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [145]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [146]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [147]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

IDENTITY AND EYE

In [148]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [149]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [150]:
np.eye(0, 4)

array([], shape=(0, 4), dtype=float64)

In [151]:
np.eye(0, 4, k=1)

array([], shape=(0, 4), dtype=float64)

In [153]:
np.eye(0, 4, k=-3)

array([], shape=(0, 4), dtype=float64)